select
		smn_inventario.smn_movimiento_detalle_desc_ret.smn_movimiento_detalle_desc_ret_id,
select
		smn_inventario.smn_movimiento_detalle_desc_ret.smn_movimiento_detalle_desc_ret_id,
select
		smn_inventario.smn_movimiento_detalle_desc_ret.smn_movimiento_detalle_desc_ret_id,
	smn_inventario.smn_movimiento_detalle_desc_ret.smn_codigo_descuento_rf,
	smn_inventario.smn_movimiento_detalle_desc_ret.mdd_monto_base_ml,
	smn_inventario.smn_movimiento_detalle_desc_ret.smn_porcentaje_rf
	
from
	smn_inventario.smn_movimiento_detalle_desc_ret
