INSERT INTO smn_inventario.smn_movimiento_detalle_impuesto
(
	smn_mov_det_impuesto_id,
	smn_movimiento_detalle_id,
	smn_cod_impuesto_deduc_rf,
	mdi_monto_base,
	smn_porcentaje_impuesto_rf,
	mdi_sustraendo_rf,
	mdi_tipo_movimiento,
	mdi_monto_impuesto_ml,
	smn_moneda,
	smn_tasa,
	mdi_monto_impuesto_ma,
	mdi_idioma,
	mdi_usuario,
	mdi_fecha_registro,
	mdi_hora
)
VALUES
(
	nextval('smn_inventario.seq_smn_movimiento_detalle_impuesto'),
	${fld:id},
	${fld:smn_codigos_impuestos_id},
	${fld:subtotal_monto_neto_ml},
	${fld:imp_porcentaje_calculo},
	${fld:imp_monto_sustraendo},
	${fld:imp_tipo_codigo},
	${fld:total_impuesto_ml_redondeo},
	${fld:smn_moneda_rf_detalle},
	${fld:smn_tasa_rf_detalle},
	${fld:total_impuesto_ma_redondeo},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
);