select 
	smn_base.smn_item.itm_nombre as smn_caracteristica_item_id,
	smn_base.smn_codigos_impuestos.imp_descripcion as smn_codigo_impuesto_rf
from
	smn_inventario.smn_rel_item_cod_impuesto
	inner join smn_inventario.smn_caracteristica_item on smn_inventario.smn_caracteristica_item.smn_caracteristica_item_id = smn_inventario.smn_rel_item_cod_impuesto.smn_caracteristica_item_id
	inner join smn_base.smn_item on smn_base.smn_item.smn_item_id = smn_inventario.smn_caracteristica_item.smn_item_rf
	inner join smn_base.smn_codigos_impuestos on smn_base.smn_codigos_impuestos.smn_codigos_impuestos_id = smn_inventario.smn_rel_item_cod_impuesto.smn_codigo_impuesto_rf
where
	smn_inventario.smn_rel_item_cod_impuesto.smn_caracteristica_item_id = ${fld:id}