INSERT INTO smn_inventario.smn_rel_item_almacen
(
	smn_rel_item_almacen_id,
	smn_caracteristica_item_id,
	smn_almacen_rf,
	ria_cantidad_max,
	ria_cantidad_min,
	ria_punto_reorden,
	ria_cantidad_seguridad
)
VALUES
(
	${seq:currval@smn_inventario.seq_smn_rel_item_almacen},
	${fld:smn_caracteristica_item_id},
	${fld:smn_almacen_rf},
	${fld:ria_cantidad_min},
	${fld:ria_cantidad_max},
	${fld:ria_punto_reorden},
	${fld:ria_cantidad_seguridad}
)
