INSERT INTO smn_inventario.smn_valoracion_conteo_fisico
(
	smn_valoracion_conteo_fisico_id,
	smn_almacen_rf,
	smn_conteo_id,
	smn_documento_id,
	vcf_numero_documento,
	smn_item_id,
	vcf_cantidad_contada,
	vcf_cantidad_existencia,
	vcf_cantidad_diferencia,
	smn_unidad_medida_almacenaje_id,
	vcf_costo_ml,
	vcf_costo_ma,
	vcf_monto_ml,
	smn_tasa_rf,
	smn_moneda_rf,
	vcf_monto_ma,
	vcf_estatus,
	vcf_idioma,
	vcf_usuario,
	vcf_fecha_registro,
	vcf_hora
)
VALUES
(
	${seq:currval@smn_inventario.seq_smn_valoracion_conteo_fisico},
	${fld:smn_almacen_rf},
	${fld:smn_conteo_id},
	${fld:smn_documento_id},
	${fld:vcf_numero_documento},
	${fld:smn_item_id},
	${fld:vcf_cantidad_contada},
	${fld:vcf_cantidad_existencia},
	${fld:vcf_cantidad_diferencia},
	${fld:smn_unidad_medida_almacenaje_id},
	${fld:vcf_costo_ml},
	${fld:vcf_costo_ma},
	${fld:vcf_monto_ml},
	${fld:smn_tasa_rf},
	${fld:smn_moneda_rf},
	${fld:vcf_monto_ma},
	${fld:vcf_estatus},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
);


