INSERT INTO smn_inventario.smn_rol
(
	smn_rol_id,
	smn_usuarios_rf,
	rol_tipo,
	smn_corporaciones_rf,
	smn_entidades_rf,
	smn_sucursales_rf,
	smn_areas_servicios_rf,
	smn_unidades_servicios_rf,
	rol_posicion_estructura_rf,
	rol_estatus,
	rol_vigencia,
	rol_idioma,
	rol_usuario,
	rol_fecha_registro,
	rol_hora,
	smn_almacen_rf
)
VALUES
(
	${seq:currval@smn_inventario.seq_smn_rol},
	${fld:smn_usuarios_rf},
	${fld:rol_tipo},
	${fld:smn_corporaciones_rf},
	${fld:smn_entidades_rf},
	${fld:smn_sucursales_rf},
	${fld:smn_areas_servicios_rf},
	${fld:smn_unidades_servicios_rf},
	${fld:rol_posicion_estructura_rf},
	${fld:rol_estatus},
	${fld:rol_vigencia},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	${fld:smn_almacen_rf},
)
