INSERT INTO smn_compras.smn_requisicion_detalle (
	smn_requisicion_detalle_id,
	smn_requisicion_cabecera_id,
	smn_linea_id,
	smn_naturaleza_id,
	smn_servicio_id,
	smn_item_id,
	smn_afijo_id ,
	rrs_producto_encontrado,
	smn_contrato_id,
	rrs_motivo_variacion,
	rrs_porcentaje,
	rss_cantidad,
	rrs_precio,
	rrs_monto,
	smn_moneda_id,
	rrs_precio_moneda_alterna,
	rrs_monto_moneda_alterna,
	smn_proveedor_id,
	rrs_especificaciones_del_requerimiento,
	rrs_fecha_de_requerido,
	rrs_observaciones,
	rrs_idioma,
 	rrs_usuario,
	rrs_fecha_registro,
	rrs_hora
)VALUES(
	nextval('smn_compras.seq_smn_requisicion_detalle'),
	(select last_value from smn_compras.seq_smn_requisicion_detalle),
	${fld:smn_linea_id},
	${fld:smn_naturaleza_id},
	${fld:smn_servicio_id},
	${fld:smn_item_rf},
	${fld:smn_afijo_id},
	${fld:rrs_producto_encontrado},
	${fld:smn_contrato_id} ,
	${fld:rrs_motivo_variacion},
	${fld:rrs_porcentaje},
	${fld:rss_cantidad},
	${fld:rrs_precio},
	${fld:rrs_monto},
	${fld:smn_moneda_id},
	${fld:rrs_precio_moneda_alterna},
	${fld:rrs_monto_moneda_alterna},
	${fld:smn_proveedor_id},
	${fld:rrs_especificaciones_del_requerimiento},
	${fld:rrs_fecha_de_requerido},
	${fld:rrs_observaciones},  
	'${def:locale}',
    '${def:user}',
    {d '${def:date}'},
    '${def:time}'
)