INSERT INTO smn_inventario.smn_movimiento_detalle
(
	smn_movimiento_detalle_id,
	smn_movimiento_cabecera_id,
	smn_item_rf,
	smn_centro_costo_rf,
	mde_lote,
	mde_fecha_vencimiento_lote,
	mde_tipo_movimiento,
	mde_cantidad_recibida,
	mde_descripcion,
	mde_es_bonificacion,
	smn_unidad_medida_rf,
	mde_valor_unitario_ml,
	smn_tasa_rf,
	smn_moneda_rf,
	mde_valor_unitario_ma,
	mde_monto_bruto_ml,
	mde_monto_bruto_ma,
	mde_monto_disminucion_ml,
	mde_monto_disminucion_ma,
	mde_monto_valor_agregado_ml,
	mde_monto_valor_agregado_ma,
	mde_monto_neto_ml,
	mde_monto_neto_ma,
	mde_estatus,
	mde_idioma,
	mde_usuario,
	mde_fecha_registro,
	mde_hora,
	mde_cantidad_solicitada,
	mde_cantidad_por_recibir,
	mde_valor_unitario_ml_origen,
	mde_cantidad,
	smn_precio_ml,
	smn_precio_ma
)
VALUES
(
	${seq:nextval@smn_inventario.seq_smn_movimiento_detalle},
	(select last_value from smn_inventario.seq_smn_movimiento_cabecera),
	${fld:smn_item_id},
	${fld:smn_centro_costo_rf},
	${fld:vcf_lote},
	${fld:vcf_fecha_vencimiento_lote},
	${fld:tipo_movimiento},
	${fld:vcf_cantidad_diferencia},
	${fld:descripcion},
	'N',
	${fld:smn_unidad_medida_almacenaje_id},
	${fld:vcf_costo_ml},
	${fld:smn_tasa_rf},
	${fld:smn_moneda_rf},
	${fld:vcf_costo_ma},
	${fld:vcf_monto_ml},
	${fld:vcf_monto_ma},
	0,
	0,
	0,
	0,
	${fld:vcf_monto_ml},
	${fld:vcf_monto_ma},
	'GE',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}',
	(case when ${fld:vcf_cantidad_contada} is null then 0 else ${fld:vcf_cantidad_contada} end),
	0,
	0,
	(case when ${fld:vcf_cantidad_contada} is null then 0 else ${fld:vcf_cantidad_contada} end),
	0,
	0

);



