select
	smn_inventario.smn_movimiento_cabecera.smn_movimiento_cabecera_id,
	smn_inventario.smn_movimiento_cabecera.mca_estatus_proceso as mca_estatus_proceso_pl0,
select
	smn_inventario.smn_control_recepcion_parcial.smn_movimiento_cabecera_id,
	smn_inventario.smn_control_recepcion_parcial.smn_orden_compra_rf,
	smn_inventario.smn_control_recepcion_parcial.crp_numero_documento,
	smn_inventario.smn_control_recepcion_parcial.smn_item_id,
	smn_inventario.smn_control_recepcion_parcial.crp_cantidad_recibida,
	smn_inventario.smn_control_recepcion_parcial.crp_fecha_recepcion,
	smn_inventario.smn_control_recepcion_parcial.crp_lote,
	smn_inventario.smn_control_recepcion_parcial.crp_fecha_vencimiento_lote,
	smn_inventario.smn_control_recepcion_parcial.crp_fecha_registro,
	smn_inventario.smn_control_recepcion_parcial.smn_control_recepcion_id
	
from
	smn_inventario.smn_movimiento_cabecera,
	smn_inventario.smn_control_recepcion_parcial
where
	smn_control_recepcion_id is not null
	and 	smn_inventario.smn_movimiento_cabecera.smn_movimiento_cabecera_id=smn_inventario.smn_control_recepcion_parcial.smn_movimiento_cabecera_id
	${filter}
order by
		smn_control_recepcion_id
