INSERT INTO smn_inventario.smn_caracteristica_almacen
(
	smn_caracteristica_almacen_id,
	smn_almacen_rf,
	cal_tipo_almacen,
	cal_capacidad_almacenaje,
	smn_unidad_medida_rf,
	cal_espacio_fisico,
	smn_unidad_medida_espacio_fisico_rf,
	cal_politica_recepcion,
	cal_estatus,
	cal_vigencia_desde,
	cal_vigencia_hasta,
	cal_control_ubicacion,
	smn_auxiliar_rf,
	smn_centro_costo_rf,
	cal_tipo_calculo_costo,
	cal_idioma,
	cal_usuario,
	cal_fecha_registro,
	cal_hora
)
VALUES
(
	${seq:currval@smn_inventario.seq_smn_caracteristica_almacen},
	${fld:smn_almacen_rf},
	${fld:cal_tipo_almacen},
	${fld:cal_capacidad_almacenaje},
	${fld:smn_unidad_medida_rf},
	${fld:cal_espacio_fisico},
	${fld:smn_unidad_medida_espacio_fisico_rf},
	${fld:cal_politica_recepcion},
	${fld:cal_estatus},
	${fld:cal_vigencia_desde},
	${fld:cal_vigencia_hasta},
	${fld:cal_control_ubicacion},
	${fld:smn_auxiliar_rf},
	${fld:smn_centro_costo_rf},
	${fld:cal_tipo_calculo_costo},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
