select
		smn_inventario.smn_rel_item_cod_impuesto.smn_rel_item_cod_impuesto_id,
select
		smn_inventario.smn_rel_item_cod_impuesto.smn_rel_item_cod_impuesto_id,
select
		smn_inventario.smn_rel_item_cod_impuesto.smn_rel_item_cod_impuesto_id,
	smn_inventario.smn_rel_item_cod_impuesto.smn_caracteristica_item_id,
	smn_inventario.smn_rel_item_cod_impuesto.smn_codigo_impuesto_rf
	
from
	smn_inventario.smn_rel_item_cod_impuesto
