INSERT INTO smn_inventario.smn_control_lote
(
	smn_control_lote_id,
	smn_entidad_rf,
	smn_sucursal_rf,
	smn_caracteristica_almacen_id,
	smn_caracteristica_item_id,
	col_lote,
	col_fecha_vencimiento,
	col_cantidad_inicial,
	col_entradas,
	col_salidas,
	col_cantidad_final,
	col_idioma,
	col_usuario,
	col_fecha_registro,
	col_hora
)
VALUES
(
	${seq:currval@smn_inventario.seq_smn_control_lote},
	${fld:smn_entidad_rf},
	${fld:smn_sucursal_rf},
	${fld:smn_caracteristica_almacen_id},
	${fld:smn_caracteristica_item_id},
	${fld:col_lote},
	${fld:col_fecha_vencimiento},
	${fld:col_cantidad_inicial},
	${fld:col_entradas},
	${fld:col_salidas},
	${fld:col_cantidad_final},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
